/**
 * Stylelint: функциональный / логический порядок свойств.
 *
 * Группы (снаружи внутрь):
 * 1. CSS Modules `composes`
 * 2. Custom properties (через order/order)
 * 3. Позиционирование и display
 * 4. Размер бокса
 * 5. Отступы (margin / padding)
 * 6. Рамка
 * 7. Типографика
 * 8. Визуал (color, background, shadow…)
 * 9. Transition / animation
 *
 * Пустая строка между логическими группами (order/properties-order emptyLineBefore).
 *
 * @type {import('stylelint').Config}
 */
const propertyGroups = [
	{
		groupName: 'composes',
		properties: ['composes'],
		emptyLineBefore: 'always',
		noEmptyLineBetween: true,
	},
	{
		groupName: 'positioning',
		properties: [
			'position',
			'inset',
			'inset-block',
			'inset-block-start',
			'inset-block-end',
			'inset-inline',
			'inset-inline-start',
			'inset-inline-end',
			'top',
			'right',
			'bottom',
			'left',
			'z-index',
		],
		emptyLineBefore: 'always',
		noEmptyLineBetween: true,
	},
	{
		groupName: 'display',
		properties: [
			'display',
			'visibility',
			'content',
			'box-sizing',
			'float',
			'clear',
			'overflow',
			'overflow-x',
			'overflow-y',
			'overscroll-behavior',
			'overscroll-behavior-x',
			'overscroll-behavior-y',
			'-webkit-overflow-scrolling',
			'clip',
			'clip-path',
			'isolation',
			'contain',
			'container-type',
			'container-name',
			'container',
		],
		emptyLineBefore: 'always',
		noEmptyLineBetween: true,
	},
	{
		groupName: 'flex-grid',
		properties: [
			'flex',
			'flex-grow',
			'flex-shrink',
			'flex-basis',
			'flex-direction',
			'flex-wrap',
			'flex-flow',
			'order',
			'justify-content',
			'justify-items',
			'justify-self',
			'align-content',
			'align-items',
			'align-self',
			'place-content',
			'place-items',
			'place-self',
			'gap',
			'row-gap',
			'column-gap',
			'grid',
			'grid-area',
			'grid-template',
			'grid-template-areas',
			'grid-template-rows',
			'grid-template-columns',
			'grid-auto-rows',
			'grid-auto-columns',
			'grid-auto-flow',
			'grid-row',
			'grid-row-start',
			'grid-row-end',
			'grid-column',
			'grid-column-start',
			'grid-column-end',
		],
		emptyLineBefore: 'always',
		noEmptyLineBetween: true,
	},
	{
		groupName: 'size',
		properties: [
			'width',
			'min-width',
			'max-width',
			'height',
			'min-height',
			'max-height',
			'inline-size',
			'min-inline-size',
			'max-inline-size',
			'block-size',
			'min-block-size',
			'max-block-size',
			'aspect-ratio',
			'object-fit',
			'object-position',
		],
		emptyLineBefore: 'always',
		noEmptyLineBetween: true,
	},
	{
		groupName: 'spacing',
		properties: [
			'margin',
			'margin-top',
			'margin-right',
			'margin-bottom',
			'margin-left',
			'margin-block',
			'margin-block-start',
			'margin-block-end',
			'margin-inline',
			'margin-inline-start',
			'margin-inline-end',
			'padding',
			'padding-top',
			'padding-right',
			'padding-bottom',
			'padding-left',
			'padding-block',
			'padding-block-start',
			'padding-block-end',
			'padding-inline',
			'padding-inline-start',
			'padding-inline-end',
			'scroll-margin',
			'scroll-padding',
			'scroll-padding-block',
		],
		emptyLineBefore: 'always',
		noEmptyLineBetween: true,
	},
	{
		groupName: 'border',
		properties: [
			'border',
			'border-width',
			'border-style',
			'border-color',
			'border-top',
			'border-top-width',
			'border-top-style',
			'border-top-color',
			'border-right',
			'border-right-width',
			'border-right-style',
			'border-right-color',
			'border-bottom',
			'border-bottom-width',
			'border-bottom-style',
			'border-bottom-color',
			'border-left',
			'border-left-width',
			'border-left-style',
			'border-left-color',
			'border-block',
			'border-block-width',
			'border-block-style',
			'border-block-color',
			'border-block-start',
			'border-block-start-width',
			'border-block-start-style',
			'border-block-start-color',
			'border-block-end',
			'border-block-end-width',
			'border-block-end-style',
			'border-block-end-color',
			'border-inline',
			'border-inline-width',
			'border-inline-style',
			'border-inline-color',
			'border-inline-start',
			'border-inline-start-width',
			'border-inline-start-style',
			'border-inline-start-color',
			'border-inline-end',
			'border-inline-end-width',
			'border-inline-end-style',
			'border-inline-end-color',
			'border-radius',
			'border-top-left-radius',
			'border-top-right-radius',
			'border-bottom-right-radius',
			'border-bottom-left-radius',
			'border-start-start-radius',
			'border-start-end-radius',
			'border-end-start-radius',
			'border-end-end-radius',
			'border-image',
			'border-image-source',
			'border-image-slice',
			'border-image-width',
			'border-image-outset',
			'border-image-repeat',
			'outline',
			'outline-width',
			'outline-style',
			'outline-color',
			'outline-offset',
		],
		emptyLineBefore: 'always',
		noEmptyLineBetween: true,
	},
	{
		groupName: 'typography',
		properties: [
			'font',
			'font-family',
			'font-size',
			'font-weight',
			'font-style',
			'font-variant',
			'font-variant-numeric',
			'font-feature-settings',
			'line-height',
			'letter-spacing',
			'word-spacing',
			'text-align',
			'text-align-last',
			'text-indent',
			'text-transform',
			'text-decoration',
			'text-decoration-line',
			'text-decoration-style',
			'text-decoration-color',
			'text-decoration-thickness',
			'text-underline-offset',
			'text-overflow',
			'text-shadow',
			'text-wrap',
			'white-space',
			'word-break',
			'overflow-wrap',
			'hyphens',
			'vertical-align',
			'list-style',
			'list-style-type',
			'list-style-position',
			'list-style-image',
			'quotes',
			'tab-size',
			'user-select',
			'caret-color',
		],
		emptyLineBefore: 'always',
		noEmptyLineBetween: true,
	},
	{
		groupName: 'visual',
		properties: [
			'color',
			'opacity',
			'background',
			'background-color',
			'background-image',
			'background-position',
			'background-position-x',
			'background-position-y',
			'background-size',
			'background-repeat',
			'background-origin',
			'background-clip',
			'background-attachment',
			'background-blend-mode',
			'fill',
			'stroke',
			'stroke-width',
			'stroke-linecap',
			'stroke-linejoin',
			'stroke-dasharray',
			'stroke-dashoffset',
			'box-shadow',
			'filter',
			'backdrop-filter',
			'mix-blend-mode',
			'mask',
			'mask-image',
			'mask-size',
			'mask-position',
			'mask-repeat',
		],
		emptyLineBefore: 'always',
		noEmptyLineBetween: true,
	},
	{
		groupName: 'tables',
		properties: [
			'table-layout',
			'border-collapse',
			'border-spacing',
			'caption-side',
			'empty-cells',
		],
		emptyLineBefore: 'always',
		noEmptyLineBetween: true,
	},
	{
		groupName: 'interaction',
		properties: [
			'cursor',
			'pointer-events',
			'touch-action',
			'resize',
			'scroll-behavior',
			'scroll-snap-type',
			'scroll-snap-align',
			'appearance',
			'-webkit-appearance',
		],
		emptyLineBefore: 'always',
		noEmptyLineBetween: true,
	},
	{
		groupName: 'transform',
		properties: [
			'transform',
			'transform-origin',
			'transform-box',
			'transform-style',
			'perspective',
			'perspective-origin',
			'backface-visibility',
			'translate',
			'rotate',
			'scale',
		],
		emptyLineBefore: 'always',
		noEmptyLineBetween: true,
	},
	{
		groupName: 'animation',
		properties: [
			'transition',
			'transition-property',
			'transition-duration',
			'transition-timing-function',
			'transition-delay',
			'animation',
			'animation-name',
			'animation-duration',
			'animation-timing-function',
			'animation-delay',
			'animation-iteration-count',
			'animation-direction',
			'animation-fill-mode',
			'animation-play-state',
			'will-change',
		],
		emptyLineBefore: 'always',
		noEmptyLineBetween: true,
	},
];

export default {
	plugins: [
		'stylelint-order',
		'@stylistic/stylelint-plugin',
	],
	ignoreFiles: [
		'**/dist/**',
		'**/dist-storybook/**',
		'**/node_modules/**',
		'**/coverage/**',
	],
	overrides: [
		{
			files: ['**/*.{css,module.css}'],
			rules: {
				'property-no-unknown': [
					true,
					{
						ignoreProperties: ['composes'],
					},
				],
				'selector-pseudo-class-no-unknown': [
					true,
					{
						ignorePseudoClasses: ['global', 'local', 'export'],
					},
				],
			},
		},
	],
	rules: {
		/* Форматирование: одно свойство на строку, переносы у `{` / `}` */
		'@stylistic/block-opening-brace-newline-after': 'always',
		'@stylistic/block-opening-brace-space-after': 'never-single-line',
		'@stylistic/block-closing-brace-newline-before': 'always',
		'@stylistic/block-closing-brace-newline-after': 'always',
		'@stylistic/block-closing-brace-space-before': 'never-single-line',
		'@stylistic/indentation': 2,
		'@stylistic/declaration-block-semicolon-newline-after': 'always',
		'@stylistic/declaration-block-semicolon-space-after': 'never-single-line',
		'order/order': [
			['custom-properties', 'declarations'],
			{unspecified: 'ignore'},
		],
		'order/properties-order': [
			propertyGroups,
			{
				unspecified: 'bottom',
				emptyLineBeforeUnspecified: 'always',
			},
		],
	},
};
